name: CI with Cache

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache example directory
        id: cache
        uses: actions/cache@v4
        with:
          path: cache-dir
          key: cache-545098e
          restore-keys: |
            cache-

      - name: prime-cache-545098e
        run: echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"

      - name: Create file in cache
        run: |
          mkdir -p cache-dir
          echo "cached content" > cache-dir/test.txt
